version: '3.9'

services:
  app:
    container_name: base_app
    env_file:
      - ./app/.env
    build:
      context: .
      dockerfile: .docker/app/local.dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - base-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
       - ./app/.env
    ports:
      - "4141:3306"
    volumes:
      - /sql
      - /var/lib/mysql
    networks:
      - base-network

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./app:/var/www/html:delegated
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '8181:80'
    networks:
      - base-network
    depends_on:
      - app

networks:
  base-network:

volumes:
  db: